### ISSUE TITLE
Create a BandService

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-sp-2022/bands-n-fans#16]
As an application I want a BandService I can depend on that will be responsible for retrieving both a single band result and a list of bands result, optionally filtered by basic search parameters.

Acceptance Criteria:
- A BandService with the following public methods:
  - getBandById with `$id` param
  - getBands with optional `$orderBy`, `$direction`, and `$limit` params
  - searchBandsByName with the `$name` param
  - update the BandController to depend on this service and call `getBands` in the /bands route
    - make sure the route is using this controller endpoint 
  - update the BandController to call `getBandById` in the /band/{id} route
    - make sure the route is using this controller endpoint 
  - update the SearchController to depend on this service and call `searchBandsByName` in the /search-results route

**Comment by jimmymccue** [comment]
Not sure why this issue is still not closed out.
