### ISSUE TITLE
Create a single band route and view

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-sp-2022/bands-n-fans#6]
As a fan user I want a page where I can view a band's information, such as bio, discography, shows, etc.

Acceptance Criteria:
- As mentioned in #5 we need a BandController to handle routes pertaining to bands
- There is a route called /bands/{id} that takes a band id parameter
- There is a view called band-info loaded by the above route
- We can get to this screen from the band list view
- For now some static placeholder band info will suffice

**Comment by oldskoolfan** [comment]
@Shahemc I'm not seeing this route/view, is this issue supposed to be closed?

**Comment by wtjoe** [comment]
I reopened this, @Shahemc can you push up your changes from this issue and associate the PR?
